<template>
  <div
    class="row py-5"
  >
    <div
      class="col-md-8"
    >
      <h3>
        About:
      </h3>

      <p>
        CURRICLE is a platform for course discovery across the Harvard curriculum, past and present. When completed, the platform will offer a full suite of tools for understanding current course offerings, charting schedules and sequencing courses in concentration and distribution, and developing a calendar of classes over the term, the year, and an entire degree program. Unlike conventional course selection systems, Curricle reveals the curriculum not as a mere listing of courses but as a dynamic network of connections that, like a living organism, evolves over time.
      </p>

      <p>
        Curricle accomplishes these tasks through three modes of operation: EXPLORE, SEARCH, and PLAN.
      </p>

      <p>
        EXPLORE offers vivid, intuitive, and interactive data visualizations for highlighting connections among courses, topics, fields, and instructors.
      </p>

      <p>
        SEARCH provides a customizable interface for data-driven keyword search of course descriptions, instructors, and meeting times.
      </p>

      <p>
        PLAN presents a robust set of organizing, tagging, and anntation tools to sequence courses across weekly, yearly, and multi-year views.
      </p>

      <p>
        Still in beta testing, Curricle is not a replacement for my.harvard, Harvard University's official course-selection tool. It complements that system and similar platforms at other colleges and universities. Built upon current and historic course data from the Office of the Registrar, its future datasets will include sources like Canvas, library reserves, linked semantic data, and student-created tags. In order to ensure an optimal user experience, it eliminates duplications in the Registrar’s database, so search results between the two platforms will differ.
      </p>

      <p>
        The Curricle team welcomes feedback and ideas for further development.
        While the platform is being tested and improved, feel free to explore, and to let us know what you find.
        Make use of the
        <a
          target="_blank"
          href="https://docs.google.com/forms/d/e/1FAIpQLSfZdL8a7O51UCurjNinVRx0RJI8ahBdUIf0uHcoNfDt6--Elw/viewform?usp=sf_link"
        >
          feedback form
        </a>
        to report bugs and issues. For general inquiries, send us an email at
        <a
          href="mailto:info@metalab.harvard.edu"
        >
          info@metalab.harvard.edu
        </a>
      </p>

      <p>
        HISTORY
      </p>

      <p>
        The Curricle project began in 2015, when then-dean of Humanities Diana Sorensen challenged metaLAB to envision a course selection tool driven by a liberal-arts spirit of inquiry. The project has been supported by the office of the Division of Arts and Humanities and the current dean, Robin Kelsey, with significant financial support from the Provost's Office and the Richard Menschel Fund to foster innovation in the humanities. The Curricle team is based in metaLAB (at) Harvard and its institutional home in the Berkman Klein Center for Internet and Society at Harvard University. Thanks are due to members of that team, past and present. At Berkman, Jon Murley has provided critical administrative and financial oversight. Director of Technology Sebastian Diaz has overseen Curricle technical development. At metaLAB, creative technologist Jessica Yurkofsky has driven the design and development of Curricle at every stage of the project. Creative Researcher Sarah Newman contributed crucially to the design and intellectual direction of the project. Interns Maia Suazo-Maler, Snow Dong, Sinead Danaher, and Berkman intern Dash El-Hauge contributed student perspectives, ingenuity, and intellectual energy. Jeffrey Schnapp, founder and faculty director of metaLAB, has provided vision and leadership throughout the project. Curricle has also benefited from advice and discussion generated by the Curriculum Mapping Working Group at the Harvard Institute for Learning and Teaching led by Erin Driver-Linn and Jaime Goldstein.
      </p>
    </div>
  </div>
</template>
