#import "./AnnotationFragment.gql"

mutation annotationSet(
  $text: String!,
  $courseId: ID!,
  $id: ID
) {
  annotationSet(
    text: $text,
    courseId: $courseId,
    id: $id
  ) {
    errors
    annotation {
      ...Annotation
    }
  }
}
