query CourseCounts(
  $semester: SemesterInput,
  $semesterRange: SemesterRangeInput
) {
  course_counts(
    semester: $semester,
    semester_range: $semesterRange
  ) {
    component
    department
    count
  }
}
