query CourseCounts(
  $basic: String,
  $courseLevels: [CourseLevel!],
  $filtered: Boolean,
  $semesterRange: SemesterRange
) {
  courseCounts(
    basic: $basic,
    courseLevels: $courseLevels,
    filtered: $filtered,
    semesterRange: $semesterRange
  ) {
    component
    department
    count
  }
}
