#import "./CourseFragment.gql"
#import "./FacetFragment.gql"

query CoursesSearch(
  $basic: String,
  $components: [Component!],
  $courseLevels: [CourseLevel!],
  $deluxeKeywords: [DeluxeKeyword!],
  $departments: [Department!],
  $ids: [ID!],
  $page: Int,
  $perPage: Int,
  $schools: [School!],
  $semesterRange: SemesterRange,
  $sortBy: CourseSortField,
  $subjects: [Subject!],
  $timeRanges: [TimeRange!]
) {
    coursesConnection(
      basic: $basic,
      components: $components,
      courseLevels: $courseLevels,
      deluxeKeywords: $deluxeKeywords,
      departments: $departments,
      ids: $ids,
      page: $page,
      perPage: $perPage,
      schools: $schools,
      semesterRange: $semesterRange,
      sortBy: $sortBy,
      subjects: $subjects,
      timeRanges: $timeRanges
    ) {
        edges {
          node {
            ...Course
          }
        }
        subjects {
          ...Facet
        }
        academicGroups {
          ...Facet
        }
        components {
          ...Facet
        }
        departments {
          ...Facet
        }
        totalCount
      }
  }
