#import "./CourseFragment.gql"
query CoursesConnectedByInstructor(
  $instructorName: String!,
  $semester: Semester!
) {
    coursesConnectedByInstructor(
      name: $instructorName,
      semester: $semester
    ) {
      ...Course
      }
  }
