fragment Course on Course {
  academic_group
  academic_group_description
  catalog_number
  class_section
  component
  course_description
  course_description_long
  external_course_id
  grading_basis_description
  id
  subject
  term_name
  term_year
  title
  units_maximum
  annotation {
    id
    text
  }
  course_instructors {
    display_name
    id
  }
  course_meeting_patterns {
    id
    meeting_time_start_tod
    meeting_time_end_tod
    meets_on_monday
    meets_on_tuesday
    meets_on_wednesday
    meets_on_thursday
    meets_on_friday
    meets_on_saturday
    meets_on_sunday
  }
}
