query CourseCounts(
  $semester: Semester,
  $semesterRange: SemesterRange
) {
  courseCounts(
    semester: $semester
    semesterRange: $semesterRange
  ) {
    component
    department
    count
  }
}
