query CoursesConnectedByInstructor(
  $courseLevels: [CourseLevel!],
  $instructorName: String!,
  $semesterRange: SemesterRange!
) {
  coursesConnectedByInstructor(
    courseLevels: $courseLevels,
    name: $instructorName,
    semesterRange: $semesterRange
  ) {
      id
      component
      subjectDescription
      title
      courseInstructors {
        id
        displayName
      }
    }
}
