fragment Course on Course {
  academicGroup
  academicGroupDescription
  catalogNumber
  classAcademicOrgDescription
  classSection
  component
  courseDescription
  courseDescriptionLong
  courseNote
  externalCourseId
  gradingBasisDescription
  id
  semester
  subject
  subjectAcademicOrgDescription
  subjectDescription
  termCode
  termName
  termYear
  title
  unitsMaximum
  annotation {
    id
    text
  }
  courseInstructors {
    displayName
    id
  }
  courseMeetingPatterns {
    id
    meetingTimeStartTod
    meetingTimeEndTod
    meetsOnMonday
    meetsOnTuesday
    meetsOnWednesday
    meetsOnThursday
    meetsOnFriday
    meetsOnSaturday
    meetsOnSunday
  }
  tags {
    id
    name
  }
}
