#import "./CourseFragment.gql"
#import "./FacetFragment.gql"

query CoursesSearch(
  $basic: String,
  $ids: [ID!],
  $deluxeKeywords: [DeluxeKeyword!],
  $semesterRange: SemesterRange,
  $page: Int,
  $perPage: Int,
  $sortBy: CourseSortField,
  $timeRanges: [TimeRange!],
  $schools: [School!],
  $departments: [Department!],
  $subjects: [Subject!],
  $components: [Component!]
) {
    coursesConnection(
      basic: $basic,
      ids: $ids,
      deluxeKeywords: $deluxeKeywords,
      semesterRange: $semesterRange,
      page: $page,
      perPage: $perPage,
      sortBy: $sortBy,
      timeRanges: $timeRanges,
      schools: $schools,
      departments: $departments,
      subjects: $subjects,
      components: $components
    ) {
        edges {
          node {
            ...Course
          }
        }
        subjects {
          ...Facet
        }
        academicGroups {
          ...Facet
        }
        components {
          ...Facet
        }
        departments {
          ...Facet
        }
        totalCount
      }
  }
