query CoursesConnectedByInstructor(
  $courseLevels: [CourseLevel!],
  $instructorName: String!,
  $semester: Semester!
) {
  coursesConnectedByInstructor(
    courseLevels: $courseLevels,
    name: $instructorName,
    semester: $semester
  ) {
      id
      component
      subjectDescription
      title
      courseInstructors {
        id
        displayName
      }
    }
}
