#import "./CourseFragment.gql"

query DeptCourses(
  $searchComponent: [Component!],
  $searchDepartment: [Department!],
  $semesterRange:  SemesterRange!
  $sortBy: CourseSortField,
) {
  coursesConnection(
    components: $searchComponent,
    departments: $searchDepartment,
    semesterRange: $semesterRange,
    perPage: 500,
    sortBy: $sortBy
  ) {
    edges {
      node {
        ...Course
      }
    }
  }
}
