query UserCourses($scheduleToken: String) {
  userCourses(scheduleToken: $scheduleToken) {
    id
    annotation {
      id
    }
    tags {
      id
    }
    userCourse {
      id
      includeInPath
    }
  }
}
