query UserCourses($scheduleToken: String) {
  userCourses(scheduleToken: $scheduleToken) {
    id
    includeInPath
    course {
      id
      annotation {
        id
      }
      tags {
        id
      }
    }
  }
}
