query UserCourses($scheduleToken: String) {
  user_courses(schedule_token: $scheduleToken) {
    id
    annotation {
      id
    }
    tags {
      id
    }
    user_course {
      id
      include_in_path
    }
  }
}