require_relative 'seeds/user_seeds'
require_relative 'seeds/division_mapping_seeds'
require_relative 'seeds/course_seeds'
require_relative 'seeds/course_meeting_pattern_seeds'
require_relative 'seeds/course_instructor_seeds'
require_relative 'seeds/course_reading_seeds'
